// <auto-generated />
using System;
using Infraestrutura.Configuracoes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230827192241_VolumeReservatorio")]
    partial class VolumeReservatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Entidades.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_CELULAR");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("USR_IDADE");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_NOME");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("USR_TIPO");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entidades.Entidades.Barragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaMAxima")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTURA_MAXIMA");

                    b.Property<string>("AnoConclusaoObra")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_ANO_CONCLUSAO");

                    b.Property<string>("BaciaHidrograficaAbrangencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_BACIA_HIDROGRAFICA_ABRANGENCIA");

                    b.Property<double>("ComprimentoCoroamento")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_COROAMENTO");

                    b.Property<int>("CondicaoFundacaoId")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<double>("CotaCoroamentoBarragem")
                        .HasColumnType("float")
                        .HasColumnName("DB_COTA_COROAMENTO_BARRAGEM");

                    b.Property<string>("CursoDaguaBarrado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_CURSO_DAGUA_BARRADO");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("IdadeBarragem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_IDADE_BARRAGEM");

                    b.Property<double>("LarguraCoroamentoBarragem")
                        .HasColumnType("float")
                        .HasColumnName("DB_LARGURA_COROAMENTO_BARRAGEM");

                    b.Property<string>("TipoFundacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_TIPO_FUNDACAO");

                    b.Property<int>("Tipo_Estrutura_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Tipo_Material_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Barragem");
                });

            modelBuilder.Entity("Entidades.Entidades.CaracteristicaBacia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeAltimetricaKm")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_ALTIMETRICA_KM");

                    b.Property<double>("AltitudeAltimetricaM")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_ALTIMETRICA_M");

                    b.Property<double>("AltitudeMaxima")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_MAXIMA");

                    b.Property<double>("AltitudeMinima")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_MINIMA");

                    b.Property<double>("AreaBacia")
                        .HasColumnType("float")
                        .HasColumnName("DB_AREA_BACIA");

                    b.Property<double>("AreaDrenagem")
                        .HasColumnType("float")
                        .HasColumnName("DB_AREA_DRENAGEM");

                    b.Property<double>("ComprimentoAxial")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_AXIAL");

                    b.Property<double>("ComprimentoRioPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_RIO_PRINCIPAL");

                    b.Property<double>("ComprimentoVetorialRioPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_VETORIAL_RIO_PRINCIPAL");

                    b.Property<double>("ComprimentototalRio")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_TOTAL_RIO");

                    b.Property<double>("Declividade")
                        .HasColumnType("float")
                        .HasColumnName("DB_DECLIVIDADE");

                    b.Property<string>("DefinicaoPadraoDrenagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_DEFINICAO_PADRAO_DRENAGEM");

                    b.Property<int>("EnumCaracteristicaPredominanteBacia")
                        .HasColumnType("int")
                        .HasColumnName("INT_CARACTERISTICA_PREDOMINANTE");

                    b.Property<string>("MunicipioFozRio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_MUNICIPIO_FOZ");

                    b.Property<string>("MunicipioNascenteRio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_MUNICIPIO_NASCENTE_RIO");

                    b.Property<double>("Perimetro")
                        .HasColumnType("float")
                        .HasColumnName("DB_PERIMETRO");

                    b.Property<int>("UsoSoloPredominanteId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("cursoHidrico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_CURSO_HIDRICO");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_NOME");

                    b.HasKey("Id");

                    b.HasIndex("UsoSoloPredominanteId");

                    b.ToTable("CARACTERISTICA_BACIA");
                });

            modelBuilder.Entity("Entidades.Entidades.CaracterizacaoAreaJusanteBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<int>("DistantciaKm")
                        .HasColumnType("int")
                        .HasColumnName("INT_DISTANCIA");

                    b.Property<int>("TipoEdificacaoId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("TipoEdificacaoId");

                    b.ToTable("CARACTERIZACAO_AREA_JUSANTE");
                });

            modelBuilder.Entity("Entidades.Entidades.CaracterizacaoAreaJusanteParaBarragens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int");

                    b.Property<int>("CaracterizacaoAreaJusanteBarragemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.HasIndex("CaracterizacaoAreaJusanteBarragemId");

                    b.ToTable("CARACTERIZACAO_AREA_JUSANTE_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.CondicaoFundacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("CONDICAO_FUNDACAO");
                });

            modelBuilder.Entity("Entidades.Entidades.CotaAreaVolume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaSuperficial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STR_AREA_SUPERFICIE");

                    b.Property<string>("Cota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STR_COTA");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("VolumeAcumulado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STR_VOLUME_ACUMULADO");

                    b.HasKey("Id");

                    b.ToTable("COTA_AREA_VOLUME");
                });

            modelBuilder.Entity("Entidades.Entidades.DadosGerais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("EmailEmpreendedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_EMAIL_EMPREENDEDOR");

                    b.Property<string>("EnderecoEmpreendedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_ENDERECO_EMPREENDEDOR");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STR_LATITUDE_EMPREENDEDOR");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STR_LONGITUDE_EMPREENDEDOR");

                    b.Property<string>("NomeEmpreendedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME_EMPREENDEDOR");

                    b.Property<int>("QuantidadeBarragem")
                        .HasColumnType("int")
                        .HasColumnName("INT_QUANTIDADE_BARRAGEM");

                    b.Property<string>("ResponsavelEmpreendedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_RESPONSAVEL_EMPREENDEDOR");

                    b.Property<string>("TelefoneEmpreendedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STR_TELEFONE_EMPREENDEDOR");

                    b.Property<int>("TipoEmpreendedor")
                        .HasColumnType("int")
                        .HasColumnName("INT_TIPO_EMPREENDEDOR");

                    b.HasKey("Id");

                    b.ToTable("DADOS_GERAl");
                });

            modelBuilder.Entity("Entidades.Entidades.DanoPotencialAssociado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<int>("DpaTotal")
                        .HasColumnType("int")
                        .HasColumnName("INT_DPA_TOTAL");

                    b.Property<int>("IA_Q1")
                        .HasColumnType("int")
                        .HasColumnName("INT_IA_Q1");

                    b.Property<int>("IA_Q2")
                        .HasColumnType("int")
                        .HasColumnName("INT_IA_Q2");

                    b.Property<int>("IA_Resposta")
                        .HasColumnType("int")
                        .HasColumnName("INT_IA_RESPOSTA");

                    b.Property<int>("ISE_Q1")
                        .HasColumnType("int")
                        .HasColumnName("INT_ISE_Q1");

                    b.Property<int>("ISE_Q2")
                        .HasColumnType("int")
                        .HasColumnName("INT_ISE_Q2");

                    b.Property<int>("ISE_Q3")
                        .HasColumnType("int")
                        .HasColumnName("INT_ISE_Q3");

                    b.Property<int>("ISE_Resposta")
                        .HasColumnType("int")
                        .HasColumnName("INT_ISE_RESPOSTA");

                    b.Property<int>("PPV_Q1")
                        .HasColumnType("int")
                        .HasColumnName("INT_PPV_Q1");

                    b.Property<int>("PPV_Q2")
                        .HasColumnType("int")
                        .HasColumnName("INT_PPV_Q2");

                    b.Property<int>("PPV_Q3")
                        .HasColumnType("int")
                        .HasColumnName("INT_PPV_Q3");

                    b.Property<int>("PPV_Q4")
                        .HasColumnType("int")
                        .HasColumnName("INT_PPV_Q4");

                    b.Property<int>("PPV_Resposta")
                        .HasColumnType("int")
                        .HasColumnName("INT_PPV_RESPOSTA");

                    b.Property<int>("VTR_Q1")
                        .HasColumnType("int")
                        .HasColumnName("INT_VTR_Q1");

                    b.Property<int>("VTR_Q2")
                        .HasColumnType("int")
                        .HasColumnName("INT_VTR_Q2");

                    b.Property<int>("VTR_Q3")
                        .HasColumnType("int")
                        .HasColumnName("INT_VTR_Q3");

                    b.Property<int>("VTR_Q4")
                        .HasColumnType("int")
                        .HasColumnName("INT_VTR_Q4");

                    b.Property<int>("VTR_Resposta")
                        .HasColumnType("int")
                        .HasColumnName("INT_VTR_RESPOSTA");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("DANO_POTENCIAL_ASSOCIADO");
                });

            modelBuilder.Entity("Entidades.Entidades.DescarregadorFundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ComandoDistancia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_COMANDO_DISTANCIA");

                    b.Property<double>("Comprimento")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO");

                    b.Property<double>("CotaSoleiraEntrada")
                        .HasColumnType("float")
                        .HasColumnName("DB_COTA_SOLEIRA_ENTRADA");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("Dimensao")
                        .HasColumnType("float")
                        .HasColumnName("DB_DIMENSAO");

                    b.Property<bool>("FonteAlternativaEnergia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_FONTE_ALTERNATIVA_ENERGIA");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_LOCALIZACAO");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_TIPO");

                    b.Property<bool>("TipoAcionamentoComporta")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TIPO_ACIONAMENTO_COMPORTA");

                    b.Property<string>("TipoComporta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_TIPO_COMPORTA");

                    b.HasKey("Id");

                    b.ToTable("DESCARREGADOR_FUNDO");
                });

            modelBuilder.Entity("Entidades.Entidades.DocumentacaoPerguntas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Pergunta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_PERGUNTA");

                    b.HasKey("Id");

                    b.ToTable("DOCUMENTACAO_PERGUNTAS");
                });

            modelBuilder.Entity("Entidades.Entidades.DocumentacaoProjetoConstrucaoOperacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Pergunta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_PERGUNTA");

                    b.Property<bool?>("Resposta")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_RESPOSTA");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("DOCUMENTACAO_PROJETO_CONSTRUCAO_OPERACAO");
                });

            modelBuilder.Entity("Entidades.Entidades.IndiceCaracterizacaoBH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeAltimetricaBaciaKM")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_ALTIMETRICA_BACIA_KM");

                    b.Property<double>("AltitudeAltimetricaBaciaM")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_ALTIMETRICA_BACIA_M");

                    b.Property<double>("AltitudeMaximaBacia")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_MAXIMA_BACIA");

                    b.Property<double>("AltitudeMinimaBacia")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_MINIMA_BACIA");

                    b.Property<double>("AltitudeVetorialRioPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTITUDE_VETORIAL");

                    b.Property<double>("AreaBaciaHidrografica")
                        .HasColumnType("float")
                        .HasColumnName("DB_AREA_BACIA_HIDROGRAFICA");

                    b.Property<int>("Barragem_ID")
                        .HasColumnType("int")
                        .HasColumnName("INT_BARRAGEM_ID");

                    b.Property<double>("ComprimentoAxialBacia")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_AXIAL_BACIA");

                    b.Property<double>("ComprimentoRioPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_RIO_PRINCIPAL");

                    b.Property<double>("ComprimentoTotalRioBacia")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_TOTAL_RIO");

                    b.Property<double>("ComprimentoVetorialRioPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_VETORIAL");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("Perimetro")
                        .HasColumnType("float")
                        .HasColumnName("DB_PERIMETRO");

                    b.Property<double>("ResultadoCoeficienteCompacidade")
                        .HasColumnType("float")
                        .HasColumnName("DB_COEFICIENTE_COMPACIDADE");

                    b.Property<double>("ResultadoCoeficienteManutencao")
                        .HasColumnType("float")
                        .HasColumnName("DB_COEFICIENTE_MANUTENCAO");

                    b.Property<double>("ResultadoDensidadeDrenagem")
                        .HasColumnType("float")
                        .HasColumnName("DB_DENSIDADE_DRENAGEM");

                    b.Property<double>("ResultadoFatorForma")
                        .HasColumnType("float")
                        .HasColumnName("DB_FATOR_FORMA");

                    b.Property<double>("ResultadoGradienteCanais")
                        .HasColumnType("float")
                        .HasColumnName("DB_GRADIENTE_CANAIS");

                    b.Property<double>("ResultadoIndiceCircularidade")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_INDICE_CIRCULARIDADE");

                    b.Property<double>("ResultadoIndiceRugosidade")
                        .HasColumnType("float")
                        .HasColumnName("DB_INDICE_RUGOSIDADE");

                    b.Property<double>("ResultadoRelacaoRelevo")
                        .HasColumnType("float")
                        .HasColumnName("DB_RELACAO_RELEVO");

                    b.Property<double>("ResultadoSinuosidadeCursoDagua")
                        .HasColumnType("float")
                        .HasColumnName("DB_SINUOSIDADE_CURSO_DAGUA");

                    b.HasKey("Id");

                    b.ToTable("INDICE_CARACTERIZACAO_BH");
                });

            modelBuilder.Entity("Entidades.Entidades.InformacoesComplementares", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoUltimaReforma")
                        .HasColumnType("int")
                        .HasColumnName("INT_ANO_ULTIMA_REFORMA");

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("HistoricoIndicidenteAcidente")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_HISTORICO_INCIDENTE_ACIDENTE");

                    b.Property<string>("NomeSetor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME_SETOR");

                    b.Property<string>("NumeroPortariaLicencaOperacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NUMERO_PORTARIA_LICENCA_OPERACAO");

                    b.Property<string>("NumeroPortariaOutorga")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NUMERO_PORTARIA_OUTORGA");

                    b.Property<bool>("PossuiEdificacaoLocalBarragem")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_EDIFICACAO_LOCAL");

                    b.Property<bool>("PossuiEscritorioLocalBarragem")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_ESCRITORIO_LOCAL");

                    b.Property<bool>("TemEquipeOperacaoBarragem")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_EQUIPE_OPERACAO");

                    b.Property<bool>("TemHistoricoIndicidenteAcidente")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_HISTORICO_INCIDENTE_ACIDENTE");

                    b.Property<bool>("TemLicencaOperacao")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_LICENCA_OPERACAO");

                    b.Property<bool>("TemOperador24")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_OPERADOR24");

                    b.Property<bool>("TemOutorgaConstrucao")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_OUTORGA_CONSTRUCAO");

                    b.Property<bool>("TemVigia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TEM_VIGIA");

                    b.Property<string>("VazaoMinimaRestituicaoAno")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_VAZAO_MINIMA_RESTITUICAO_ANO");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("INFORMACOES_COMPLEMENTARES");
                });

            modelBuilder.Entity("Entidades.Entidades.Inspecoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<DateTime?>("DataEstudoRompimento")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA__ESTUDO_ROMPIMENTO");

                    b.Property<DateTime?>("DataPlanoAcaoEmergencia")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_PLANO_ACAO_EMERGENCIA");

                    b.Property<DateTime?>("DataRevisaoPeriodicaRecente")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_REVISAO_PERIODICA_RECENTE");

                    b.Property<DateTime?>("DataUltimaInspecaoEspecial")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ULTIMA_INSPECAO_ESPECIAL");

                    b.Property<string>("EnumFrequencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_FREQUENCIA");

                    b.Property<string>("Nome_Setor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME_SETOR");

                    b.Property<bool>("PossuiEstudoRompimento")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_POSSUI_ESTUDO_ROMPIMENTO");

                    b.Property<bool>("PossuiPae")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_POSSUI_PAE");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("INSPECOES");
                });

            modelBuilder.Entity("Entidades.Entidades.Instrumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("INSTRUMENTOS");
                });

            modelBuilder.Entity("Entidades.Entidades.InstrumentosBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<int>("InstrumentosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.HasIndex("InstrumentosId");

                    b.ToTable("INSTRUMENTOS_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.Reservatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BordaLivre")
                        .HasColumnType("float")
                        .HasColumnName("DB_BORDA_LIVRE");

                    b.Property<double>("CapacidadeTotalReservatorio")
                        .HasColumnType("float")
                        .HasColumnName("DB_CAPACIDADE_TOTAL_RESERVATORIO");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("MaximoMaximorum")
                        .HasColumnType("float")
                        .HasColumnName("DB_MAXIMO_MAXIMORUM");

                    b.Property<double>("MaximoNormal")
                        .HasColumnType("float")
                        .HasColumnName("DB_MAXIMO_NORMAL");

                    b.Property<double>("MinimoOperacional")
                        .HasColumnType("float")
                        .HasColumnName("DB_MINIMO_OPERACIONAL");

                    b.Property<double>("VolumeMorto")
                        .HasColumnType("float")
                        .HasColumnName("DB_VOLUME_MORTO");

                    b.Property<double>("VolumeUtilReservatorio")
                        .HasColumnType("float")
                        .HasColumnName("DB_VOLUME_UTIL_RESERVATORIO");

                    b.HasKey("Id");

                    b.ToTable("RESERVATORIO");
                });

            modelBuilder.Entity("Entidades.Entidades.SistemaDrenagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("SISTEMA_DRENAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.SistemaDrenagemBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<int>("SistemaDrenagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.HasIndex("SistemaDrenagemId");

                    b.ToTable("SISTEMA_DRENAGEM_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.Talude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("InclinacaoTaludeJusante")
                        .HasColumnType("float")
                        .HasColumnName("DB_INCLINACAO_TALUDE_JUSANTE");

                    b.Property<double>("InclinacaoTaludeMontante")
                        .HasColumnType("float")
                        .HasColumnName("DB_INCLINACAO_TALUDE_MONTANTE");

                    b.Property<string>("TipoProtecaoSuperficieJusante")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_PROTECAO_SUPERFICIE_JUSANTE");

                    b.Property<string>("TipoProtecaoSuperficieMontante")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_PROTECAO_SUPERFICIE_MONTANTE");

                    b.HasKey("Id");

                    b.ToTable("TALUDE");
                });

            modelBuilder.Entity("Entidades.Entidades.TempoConcentracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaDrenagem_A")
                        .HasColumnType("float")
                        .HasColumnName("DB_AREA_DRENAGEM");

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnName("DB_BARRAGEM_ID");

                    b.Property<double>("ComprimentoRioPrincipal_L")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_RIO_PRINCIPAL");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("DeclividadeBacia_S")
                        .HasColumnType("float")
                        .HasColumnName("DB_DECLIVIDADE_BACIA");

                    b.Property<double>("ResultadoCarter")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_CARTER");

                    b.Property<double>("ResultadoCorpsEngineers")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_CORPS_ENGINEERS");

                    b.Property<double>("ResultadoDooge")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_DOOGE");

                    b.Property<double>("ResultadoKirpich")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_KIRPICH");

                    b.Property<double>("ResultadoVenTeChow")
                        .HasColumnType("float")
                        .HasColumnName("DB_RESULTADO_VEN_TE_CHOW");

                    b.HasKey("Id");

                    b.ToTable("TEMPO_CONCENTRACAO");
                });

            modelBuilder.Entity("Entidades.Entidades.TipoEdificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("TIPO_EDIFICACAO");
                });

            modelBuilder.Entity("Entidades.Entidades.TipoEmpreendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("TIPO_EMPREENDEDOR");
                });

            modelBuilder.Entity("Entidades.Entidades.TipoEstruturaBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("TIPO_ESTRUTURA_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.TipoMaterialBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("TIPO_MATERIAL_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.TomadaDagua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ComandoDistancia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_COMANDO_DISTANCIA");

                    b.Property<double>("Comprimento")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO");

                    b.Property<string>("ControleEntrada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_CONTROLE_ENTRADA");

                    b.Property<string>("ControleSaida")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_CONTROLE_Saida");

                    b.Property<double>("CotasTomadasDaguaEntrada")
                        .HasColumnType("float")
                        .HasColumnName("DB_COTAS_TOMADAS_DAGUA_ENTRADA");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<bool>("FonteAlternativaEnergia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_FONTE_ALTERNATIVA_ENERGIA");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_LOCALIZACAO");

                    b.Property<bool>("PossibilidadeManobraManual")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_POSSIBILIDADE_MANOBRA_MANUAL");

                    b.HasKey("Id");

                    b.ToTable("TOMADA_DAGUA");
                });

            modelBuilder.Entity("Entidades.Entidades.UsoBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<bool>("GeracaoEnergia")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_GERACAO_ENERGIA");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("USO_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.UsoBarragemBarragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<int>("UsoBarragemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.HasIndex("UsoBarragemId");

                    b.ToTable("USO_BARRAGEM_BARRAGEM");
                });

            modelBuilder.Entity("Entidades.Entidades.UsoSoloPredominante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_NOME");

                    b.HasKey("Id");

                    b.ToTable("USO_SOLO_PREDOMINANTE");
                });

            modelBuilder.Entity("Entidades.Entidades.VazaPico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarragemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double?>("valorAS")
                        .HasColumnType("float")
                        .HasColumnName("DB_AS");

                    b.Property<double?>("valorHhid")
                        .HasColumnType("float")
                        .HasColumnName("DB_HHID");

                    b.Property<double?>("valorVhid")
                        .HasColumnType("float")
                        .HasColumnName("DB_VHID");

                    b.Property<double?>("valorYmed")
                        .HasColumnType("float")
                        .HasColumnName("DB_YMED");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("VAZAO_PICO");
                });

            modelBuilder.Entity("Entidades.Entidades.Vertedouro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float")
                        .HasColumnName("DB_ALTURA");

                    b.Property<double>("ComprimentoTotalVertedouro")
                        .HasColumnType("float")
                        .HasColumnName("DB_COMPRIMENTO_TOTAL_VERTEDOURO");

                    b.Property<double>("CotaSoleiraVetedouro")
                        .HasColumnType("float")
                        .HasColumnName("DB_COTA_SOLEIRO");

                    b.Property<DateTime>("DataAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_CADASTRO");

                    b.Property<double>("LarguraTotalVertedouro")
                        .HasColumnType("float")
                        .HasColumnName("DB_LARGURA_TOTAL_VERTEDOURO");

                    b.Property<string>("LocalizacaoVertedouro")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_LOCALIZACAO");

                    b.Property<string>("ModalidadeDissipacaoEnergia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_MODALIDADE_DISSIPACAO_ENERGIA");

                    b.Property<int>("QuantidadeComportas")
                        .HasColumnType("int")
                        .HasColumnName("INT_QUANTIDADE_COMPORTA");

                    b.Property<int>("TempoRetornoVazaoMaximaProjetoAnos")
                        .HasColumnType("int")
                        .HasColumnName("DB_TEMPO_RETORNO_VAZAO");

                    b.Property<bool>("TipoAcionamentoComportas")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_TIPO_ACIONAMENTO_COMPORTAS");

                    b.Property<string>("TipoEstruturaExtravasoraPrincipal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STR_TIPO_ESTRUTURA_EXTRAVASORA");

                    b.Property<double>("VazaoMaximaProjetoVertedor")
                        .HasColumnType("float")
                        .HasColumnName("DB_VAZAO");

                    b.Property<bool>("VertedouroControle")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_VERTEDOURO_CONTROLE");

                    b.Property<bool>("VetedouroAuxiliar")
                        .HasColumnType("bit")
                        .HasColumnName("BOOL_VETEDOURO_AUXILIAR");

                    b.HasKey("Id");

                    b.ToTable("VERTEDOURO");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entidades.Entidades.CaracteristicaBacia", b =>
                {
                    b.HasOne("Entidades.Entidades.UsoSoloPredominante", "UsoSoloPredominante")
                        .WithMany()
                        .HasForeignKey("UsoSoloPredominanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsoSoloPredominante");
                });

            modelBuilder.Entity("Entidades.Entidades.CaracterizacaoAreaJusanteBarragem", b =>
                {
                    b.HasOne("Entidades.Entidades.TipoEdificacao", "TipoEdificacao")
                        .WithMany()
                        .HasForeignKey("TipoEdificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEdificacao");
                });

            modelBuilder.Entity("Entidades.Entidades.CaracterizacaoAreaJusanteParaBarragens", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.CaracterizacaoAreaJusanteBarragem", "CaracterizacaoAreaJusanteBarragem")
                        .WithMany()
                        .HasForeignKey("CaracterizacaoAreaJusanteBarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");

                    b.Navigation("CaracterizacaoAreaJusanteBarragem");
                });

            modelBuilder.Entity("Entidades.Entidades.DanoPotencialAssociado", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");
                });

            modelBuilder.Entity("Entidades.Entidades.DocumentacaoProjetoConstrucaoOperacao", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");
                });

            modelBuilder.Entity("Entidades.Entidades.InformacoesComplementares", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");
                });

            modelBuilder.Entity("Entidades.Entidades.Inspecoes", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");
                });

            modelBuilder.Entity("Entidades.Entidades.InstrumentosBarragem", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.Instrumentos", "Instrumentos")
                        .WithMany()
                        .HasForeignKey("InstrumentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");

                    b.Navigation("Instrumentos");
                });

            modelBuilder.Entity("Entidades.Entidades.SistemaDrenagemBarragem", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.SistemaDrenagem", "SistemaDrenagem")
                        .WithMany()
                        .HasForeignKey("SistemaDrenagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");

                    b.Navigation("SistemaDrenagem");
                });

            modelBuilder.Entity("Entidades.Entidades.UsoBarragemBarragem", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.UsoBarragem", "UsoBarragem")
                        .WithMany()
                        .HasForeignKey("UsoBarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");

                    b.Navigation("UsoBarragem");
                });

            modelBuilder.Entity("Entidades.Entidades.VazaPico", b =>
                {
                    b.HasOne("Entidades.Entidades.Barragem", "Barragem")
                        .WithMany()
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barragem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entidades.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entidades.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entidades.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
